[workspace]
authors = ["ravioli67 <s2050969@online.houstonisd.org>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "quickstart"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max-all = ">=26.7.0.dev2026100605,<27"
